async function initReport() {
  const loggedUser = getLoggedUser();
  const userData = await getData(`users/${loggedUser.id}`);

  const incomes = userData.transactions?.income || [];
  const expenses = userData.transactions?.expenses || [];

  document.getElementById("downloadCSV").onclick = () => {
    if (!hasData(incomes, expenses)) {
      showToast("No data available to download", "danger");
      return;
    }
    downloadCSV(incomes, expenses);
  };

  document.getElementById("downloadPDF").onclick = () => {
    if (!hasData(incomes, expenses)) {
      showToast("No data available to download", "danger");
      return;
    }
    downloadPDF(incomes, expenses);
  };

  document.getElementById("downloadExcel").onclick = () => {
    if (!hasData(incomes, expenses)) {
      showToast("No data available to download", "danger");
      return;
    }
    downloadExcel(incomes, expenses);
  };
}

function hasData(incomes, expenses) {
  return incomes.length > 0 || expenses.length > 0;
}

function downloadCSV(income, expenses) {
  const data = [
    ...income.map((i) => ({ ...i, type: "Income" })),
    ...expenses.map((e) => ({ ...e, type: "Expense" })),
  ];

  let csv = "Type,Source,Category,Amount,Date\n";

  data.forEach((item) => {
    csv += `${item.type},${item.sourceName},${item.category},${item.amount},${item.date}\n`;
  });

  const blob = new Blob([csv], { type: "text/csv" });
  const url = window.URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = "report.csv";
  a.click();
}

function downloadPDF(incomes, expenses) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  // Title
  doc.setFontSize(16);
  doc.text("Finance Report", 14, 15);

  // Subtitle (date)
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 22);

  // Prepare data
  const rows = [];

  const data = [
    ...incomes.map((i) => ({ ...i, type: "Income" })),
    ...expenses.map((e) => ({ ...e, type: "Expense" })),
  ];

  data.forEach((item) => {
    rows.push([
      item.type,
      item.sourceName,
      item.category,
      `Rs. ${item.amount.toLocaleString()}`,
      item.date,
    ]);
  });

  // Table
  doc.autoTable({
    startY: 30,
    head: [["Type", "Source", "Category", "Amount", "Date"]],
    body: rows,

    styles: {
      fontSize: 10,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [41, 128, 185], // blue header
      textColor: 255,
      halign: "center",
    },

    bodyStyles: {
      textColor: 50,
    },

    didParseCell: function (data) {
      // Color for Income / Expense
      if (data.column.index === 0 && data.cell.section === "body") {
        if (data.cell.raw === "Income") {
          data.cell.styles.textColor = [0, 128, 0]; // green
        } else {
          data.cell.styles.textColor = [200, 0, 0]; // red
        }
      }
    },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by Personal Finance Manager", 14, pageHeight - 10);

  // Save
  doc.save("finance_report.pdf");
}

// Excel
function downloadExcel(incomes, expenses) {
  const allData = [
    ...incomes.map((i) => ({
      Type: "Income",
      Source: i.sourceName,
      Category: i.category,
      Amount: i.amount,
      Date: i.date,
    })),
    ...expenses.map((e) => ({
      Type: "Expense",
      Source: e.sourceName,
      Category: e.category,
      Amount: e.amount,
      Date: e.date,
    })),
  ];

  // Sort by date
  allData.sort((a, b) => new Date(b.Date) - new Date(a.Date));

  const workbook = XLSX.utils.book_new();

  // 📊 Group by month
  const monthMap = {};

  allData.forEach((item) => {
    const d = new Date(item.Date);
    const month = d.toLocaleString("default", { month: "short" }); // Jan, Feb

    if (!monthMap[month]) {
      monthMap[month] = [];
    }

    monthMap[month].push(item);
  });

  // 📄 Create sheet per month
  Object.keys(monthMap).forEach((month) => {
    const worksheet = XLSX.utils.json_to_sheet(monthMap[month]);
    XLSX.utils.book_append_sheet(workbook, worksheet, month);
  });

  // Download
  XLSX.writeFile(workbook, "finance_report.xlsx");
}
